package org.drinkmore;

import androidx.annotation.Keep;

import org.thunderdog.challegram.BuildConfig;

import me.vkryl.annotation.Autogenerated;

@Autogenerated
@Keep
public abstract class ClientException extends RuntimeException {
  private ClientException (String message) {
    super(message);
  }

  private static class ClientException_1826 extends ClientException {
    private ClientException_1826 (String message) {
      super(Tracer.format(message));
    }
  }

  static final class DatabaseError extends ClientException_1826 {
    DatabaseError (String message) {
      super(message + ", versionCode: " + BuildConfig.ORIGINAL_VERSION_CODE);
    }
  }

  static final class TdlibLaunchError extends ClientException_1826 {
    TdlibLaunchError (String message) {
      super(message);
    }
  }

  static final class TdlibLostPromiseError extends ClientException_1826 {
    TdlibLostPromiseError (String message) {
      super(message);
    }
  }

  static void throwTestError (Throwable error) {
    throw new ClientException_1826(error.getMessage());
  }

  static void throwAssertionError (Throwable error) {
    throw new ClientException_1826(error.getMessage());
  }
}