package tgx.gradle.task

import groovy.util.Node
import groovy.util.NodeList
import groovy.xml.XmlParser
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.FileSystemOperations
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.*
import tgx.gradle.data.Theme
import tgx.gradle.fatal
import tgx.gradle.validateDir
import java.io.Writer
import javax.inject.Inject

@CacheableTask
abstract class GenerateThemesTask : DefaultTask() {
  @get:InputFile
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val colorsAndProperties: RegularFileProperty

  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val themeFiles: ConfigurableFileCollection

  @get:OutputDirectory
  abstract val resOutputDir: DirectoryProperty

  @get:OutputDirectory
  abstract val javaOutputDir: DirectoryProperty

  @get:OutputDirectory
  abstract val kotlinOutputDir: DirectoryProperty

  @TaskAction
  fun generateThemes () {
    val java = validateDir(javaOutputDir.get().asFile)
    val kotlin = validateDir(kotlinOutputDir.get().asFile)
    val res = validateDir(resOutputDir.get().asFile)

    val themes = XmlParser().parse(colorsAndProperties.get().asFile)

    val generatedIds = ArrayList<String>()

    // Themes

    val themeColors = ArrayList<String>()
    val fallbackColors = mutableMapOf<String, String>()
    val themeProperties = ArrayList<String>()
    val tintedColors = mutableSetOf<String>()
    val porterDuffColors = mutableSetOf<String>()

    for (item in (((themes["sections"] as NodeList)[0] as Node)["item"]) as NodeList) {
      val name = (item as Node)["@name"].toString()
      generatedIds.add("theme_category_${name}")
    }
    for (item in (((themes["properties"] as NodeList)[0] as Node)["item"]) as NodeList) {
      val name = (item as Node)["@name"].toString()
      // generatedIds.add("theme_property_${name}")
      themeProperties.add(name)
    }
    for (item in (((themes["colors"] as NodeList)[0] as Node)["item"]) as NodeList) {
      val name = (item as Node)["@name"].toString()
      val tinted = item["@tinted"]?.toString() == "true"
      val needsPorterDuff = item["@porterDuff"]?.toString() == "true"
      val fallbackColorId = item["@fallback"]?.toString()
      // generatedIds.add("theme_color_${name}")
      themeColors.add(name)
      if (tinted) {
        tintedColors.add(name)
      }
      if (needsPorterDuff) {
        porterDuffColors.add(name)
      }
      if (!fallbackColorId.isNullOrEmpty()) {
        if (fallbackColors.containsKey(fallbackColorId) || name == fallbackColorId) {
          error("Recursive fallback: $name <-> $fallbackColorId")
        }
        fallbackColors[name] = fallbackColorId
      }
    }
    for (entry in fallbackColors.entries) {
      if (!themeColors.contains(entry.value)) {
        error("Unknown fallback color id: ${entry.key} -> ${entry.value}")
      }
    }
    val themeSettingsNode = (themes["settings"] as NodeList)[0] as Node
    val defaultThemeNode = (themeSettingsNode["default-theme"] as NodeList)[0] as Node
    val sourceTheme = ((themeSettingsNode["source-theme"] as NodeList)[0] as Node).toInteger()
    val defaultLightTheme = ((defaultThemeNode["light"] as NodeList)[0] as Node).toInteger()
    val defaultDarkTheme = ((defaultThemeNode["dark"] as NodeList)[0] as Node).toInteger()

    // generated.xml

    writeToFile(
      res.resolve("values/generated.xml")
    ) { xml ->
      xml.append("""
        <?xml version="1.0" encoding="utf-8"?>
        <!-- AUTOGENERATED, DO NOT MODIFY -->
        <resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation">
        
      """.trimIndent())
      generatedIds.forEach { id ->
        xml.append(
          "  <item type=\"id\" name=\"$id\" />\n"
        )
      }
      xml.append("""
        </resources>
      """.trimIndent())
    }

    // API <= 21 fallback for local dialect strings
    for ((scriptFolder, legacyFolder) in arrayOf("b+zh+Hans" to "zh-rCN", "b+zh+Hant" to "zh-rTW")) {
      val source = File("app/src/main/res/values-$scriptFolder/moex_strings.xml")
      if (source.exists()) {
        val content = source.readText()
        writeToFile("app/src/main/res/values-$legacyFolder/moex_strings.xml") { xml ->
          xml.append(content)
        }
      }
    }

    // LangUtils.kt

    writeToFile("app/src/main/java/org/thunderdog/challegram/core/LangUtils.kt") { kt ->
      kt.append("@file:JvmName(\"LangUtils\")\n\n")
        .append("package org.thunderdog.challegram.core\n\n")
        .append("import androidx.annotation.StringRes\n")
        .append("import me.vkryl.annotation.Autogenerated\n")
        .append("import org.thunderdog.challegram.theme.ColorId\n")
        .append("import org.thunderdog.challegram.theme.PropertyId\n")

      kt.append("import org.thunderdog.challegram.R\n\n")

      kt.append("""
        @Autogenerated fun getAllKeys (): Array<Array<String>> = arrayOf(
          arrayOf(
            ${ordinaryKeys.toSortedSet().joinToString(",\n            ") { "\"$it\"" }}
          ),
          arrayOf(
            ${pluralKeys.toSortedSet().joinToString(",\n            ") { "\"$it\"" }}
          )
        )
        
        @Autogenerated fun getBlacklistedKeys (): Array<String> = arrayOf(
          ${blacklistedKeys.toSortedSet().joinToString(",\n          ") { "\"$it\"" }}
        )
        
        
      """.trimIndent())

      kt.append("@Autogenerated @StringRes fun getRelativeDateForm (@StringRes res: Int, @Lang.RelativeDateForm form: Int): Int = when (res) {\n")
      for (entry in foundRelativeDates) {
        kt.append("  R.string.").append(entry.key).append(" -> when (form) {\n")
        entry.value.forEach { form ->
          kt.append("    Lang.RelativeDateForm.").append(form.uppercase(Locale.US))
                .append(" -> ")
                .append("R.string.").append(entry.key).append("_").append(form)
                .append("\n")
        }
        kt.append("    else -> throw IllegalArgumentException(form.toString())\n")
          .append("  }\n")
      }
      kt.append("  else -> throw IllegalArgumentException(Lang.getResourceEntryName(res))\n")
        .append("}\n\n")


      kt.append("@Autogenerated @StringRes fun getColorIdDescription (@ColorId colorId: Int): Int = when (colorId) {\n")
      foundColorDescriptions.keys.forEach { key ->
        kt.append("  ColorId.")
        kt.append(key).append(" -> R.string.c_").append(key).append("\n")
      }
      kt.append("  else -> 0\n")
         .append("}\n\n")

      kt.append("@Autogenerated @StringRes fun getPropertyIdDescription (@PropertyId propertyId: Int): Int = when (propertyId) {\n")
      foundPropertyDescriptions.keys.forEach { key ->
        kt.append("  PropertyId.${key.camelCaseToUpperCase()}")
          .append(" -> R.string.p_").append(key)
          .append("\n")
      }
      kt.append("  else -> 0\n")
        .append("}\n\n")

      kt.append("@Autogenerated @StringRes fun getPluralForm (@StringRes res: Int, @Lang.PluralForm form: Int): Int = when (res) {\n")
      for (entry in foundPlurals) {
        kt.append("  R.string.").append(entry.key)
              .append(" -> when (form) {\n")
        pluralForms.forEach { form ->
          kt.append("    Lang.PluralForm.").append(form.uppercase(Locale.US))
                .append(" -> ")
                .append("R.string.").append(entry.key).append("_").append(form).append("\n")
        }
        kt.append("    else -> throw IllegalArgumentException(form.toString())\n")
        kt.append("  }\n")
      }
      kt.append("  else -> throw IllegalArgumentException(Lang.getResourceEntryName(res))\n")
        .append("}\n")
    }

